/* Generated By:JJTree&JavaCC: Do not edit this line. UQLParserConstants.java */
package org.wonderdb.parser.jtree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSERT = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int DELETE = 7;
  /** RegularExpression Id. */
  int UPDATE = 8;
  /** RegularExpression Id. */
  int WHERE = 9;
  /** RegularExpression Id. */
  int SET = 10;
  /** RegularExpression Id. */
  int INTO = 11;
  /** RegularExpression Id. */
  int VALUES = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int FROM = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int LONG = 17;
  /** RegularExpression Id. */
  int DOUBLE = 18;
  /** RegularExpression Id. */
  int FLOAT = 19;
  /** RegularExpression Id. */
  int STR = 20;
  /** RegularExpression Id. */
  int CREATE = 21;
  /** RegularExpression Id. */
  int INDEX = 22;
  /** RegularExpression Id. */
  int UNIQUE = 23;
  /** RegularExpression Id. */
  int ON = 24;
  /** RegularExpression Id. */
  int TABLE = 25;
  /** RegularExpression Id. */
  int SHOW = 26;
  /** RegularExpression Id. */
  int SCHEMA = 27;
  /** RegularExpression Id. */
  int LIKE = 28;
  /** RegularExpression Id. */
  int STORAGE = 29;
  /** RegularExpression Id. */
  int IS_DEFAULT = 30;
  /** RegularExpression Id. */
  int YES = 31;
  /** RegularExpression Id. */
  int NO = 32;
  /** RegularExpression Id. */
  int ALTER = 33;
  /** RegularExpression Id. */
  int ADD = 34;
  /** RegularExpression Id. */
  int NULL = 35;
  /** RegularExpression Id. */
  int SHARD = 36;
  /** RegularExpression Id. */
  int REPLICASET = 37;
  /** RegularExpression Id. */
  int TO = 38;
  /** RegularExpression Id. */
  int UNION = 39;
  /** RegularExpression Id. */
  int STORAGES = 40;
  /** RegularExpression Id. */
  int LOGGING = 41;
  /** RegularExpression Id. */
  int ENABLED = 42;
  /** RegularExpression Id. */
  int DISABLED = 43;
  /** RegularExpression Id. */
  int EXPLAIN = 44;
  /** RegularExpression Id. */
  int PLAN = 45;
  /** RegularExpression Id. */
  int SHUTDOWN = 46;
  /** RegularExpression Id. */
  int DEFAULT_STORAGE = 47;
  /** RegularExpression Id. */
  int UNION_ALL = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int LPAREN = 50;
  /** RegularExpression Id. */
  int RPAREN = 51;
  /** RegularExpression Id. */
  int EQUALS = 52;
  /** RegularExpression Id. */
  int NOTEQUAL = 53;
  /** RegularExpression Id. */
  int GE = 54;
  /** RegularExpression Id. */
  int LE = 55;
  /** RegularExpression Id. */
  int GT = 56;
  /** RegularExpression Id. */
  int LT = 57;
  /** RegularExpression Id. */
  int PLUS = 58;
  /** RegularExpression Id. */
  int MINUS = 59;
  /** RegularExpression Id. */
  int DIV = 60;
  /** RegularExpression Id. */
  int MUL = 61;
  /** RegularExpression Id. */
  int Q = 62;
  /** RegularExpression Id. */
  int QUOTED_STRING = 63;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 64;
  /** RegularExpression Id. */
  int NUMBER = 65;
  /** RegularExpression Id. */
  int STRING = 66;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"insert\"",
    "\"select\"",
    "\"delete\"",
    "\"update\"",
    "\"where\"",
    "\"set\"",
    "\"into\"",
    "\"values\"",
    "\"and\"",
    "\"or\"",
    "\"from\"",
    "\"int\"",
    "\"long\"",
    "\"double\"",
    "\"float\"",
    "\"string\"",
    "\"create\"",
    "\"index\"",
    "\"unique\"",
    "\"on\"",
    "\"table\"",
    "\"show\"",
    "\"schema\"",
    "\"like\"",
    "\"storage\"",
    "\"is_default\"",
    "\"yes\"",
    "\"no\"",
    "\"alter\"",
    "\"add\"",
    "\"null\"",
    "\"shard\"",
    "\"replicaset\"",
    "\"to\"",
    "\"union\"",
    "\"storages\"",
    "\"logging\"",
    "\"enabled\"",
    "\"disabled\"",
    "\"explain\"",
    "\"plan\"",
    "\"shutdown\"",
    "\"default storage\"",
    "\"union all\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<>\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"?\"",
    "<QUOTED_STRING>",
    "<SINGLE_QUOTED_STRING>",
    "<NUMBER>",
    "<STRING>",
    "\".\"",
    "\";\"",
  };

}
