/* Generated By:JavaCC: Do not edit this line. UQLParserTreeConstants.java Version 5.0 */
package org.wonderdb.parser.jtree;

public interface UQLParserTreeConstants
{
  public int JJTNUMBER = 0;
  public int JJTDECIMAL = 1;
  public int JJTPRECISION = 2;
  public int JJTCOLUMNANDALIAS = 3;
  public int JJTVOID = 4;
  public int JJTLITERALLIST = 5;
  public int JJTINSERTCOLUMNLIST = 6;
  public int JJTSELECTCOLUMNLIST = 7;
  public int JJTTABLEDEF = 8;
  public int JJTUPDATECOLUMN = 9;
  public int JJTPARSE = 10;
  public int JJTSTART = 11;
  public int JJTFILTEREXPRESSION = 12;
  public int JJTCOMPAREEQUATION = 13;
  public int JJTEQUALITYEQUATION = 14;
  public int JJTMULTIPLICATIVEEXPRESSION = 15;
  public int JJTUNARYEXPRESSION = 16;
  public int JJTGROUPEDCOMPAREEQUATION = 17;
  public int JJTPLUS = 18;
  public int JJTQ = 19;
  public int JJTSTR = 20;
  public int JJTGT = 21;
  public int JJTLT = 22;
  public int JJTGE = 23;
  public int JJTLE = 24;
  public int JJTEQ = 25;
  public int JJTNE = 26;
  public int JJTMINUS = 27;
  public int JJTMUL = 28;
  public int JJTDIV = 29;
  public int JJTAND = 30;
  public int JJTOR = 31;
  public int JJTUNION = 32;
  public int JJTUNIONALL = 33;
  public int JJTSELECTSTMT = 34;
  public int JJTINSERTSTMT = 35;
  public int JJTUPDATESTMT = 36;
  public int JJTDELETESTMT = 37;
  public int JJTIDENTIFIER = 38;
  public int JJTFN = 39;
  public int JJTCREATETABLE = 40;
  public int JJTTABLENAME = 41;
  public int JJTINDEXNAME = 42;
  public int JJTTABLECOLUMNNAME = 43;
  public int JJTTABLECOLUMNTYPE = 44;
  public int JJTCREATETABLECOLUMNDEF = 45;
  public int JJTCREATESTORAGE = 46;
  public int JJTSTORAGENAME = 47;
  public int JJTSTORAGESIZE = 48;
  public int JJTDEFAULTSTORAGE = 49;
  public int JJTCREATEINDEX = 50;
  public int JJTINDEXCOLUMN = 51;
  public int JJTFNDEF = 52;
  public int JJTFNNAME = 53;
  public int JJTUNIQUE = 54;
  public int JJTALTERTABLE = 55;
  public int JJTSHOWSTORAGES = 56;
  public int JJTSHOWSCHEMA = 57;
  public int JJTEXPLAINPLAN = 58;
  public int JJTSHOWTABLE = 59;
  public int JJTSHUTDOWN = 60;


  public String[] jjtNodeName = {
    "number",
    "decimal",
    "precision",
    "columnAndAlias",
    "void",
    "literalList",
    "insertColumnList",
    "selectColumnList",
    "tableDef",
    "updateColumn",
    "parse",
    "Start",
    "filterExpression",
    "compareEquation",
    "equalityEquation",
    "multiplicativeExpression",
    "unaryExpression",
    "groupedCompareEquation",
    "plus",
    "q",
    "str",
    "gt",
    "lt",
    "ge",
    "le",
    "eq",
    "ne",
    "minus",
    "mul",
    "div",
    "and",
    "or",
    "union",
    "unionAll",
    "selectStmt",
    "insertStmt",
    "updateStmt",
    "deleteStmt",
    "identifier",
    "fn",
    "createTable",
    "tableName",
    "indexName",
    "tableColumnName",
    "tableColumnType",
    "createTableColumnDef",
    "createStorage",
    "storageName",
    "storageSize",
    "defaultStorage",
    "createIndex",
    "indexColumn",
    "fnDef",
    "fnName",
    "unique",
    "alterTable",
    "showStorages",
    "showSchema",
    "explainPlan",
    "showTable",
    "shutdown",
  };
}
/* JavaCC - OriginalChecksum=2c086f9758a3ca6fc5933797b5acade9 (do not edit this line) */
