/* Generated By:JavaCC: Do not edit this line. FilterParserTreeConstants.java Version 5.0 */
package org.wonderdb.parser.jtree.filter;

public interface FilterParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSTART = 1;
  public int JJTAND = 2;
  public int JJTOR = 3;
  public int JJTFUNCTION = 4;
  public int JJTBOOLEANSENTENCE = 5;
  public int JJTVOID = 6;
  public int JJTSENTENCE = 7;
  public int JJTNESTEDSENTENCE = 8;


  public String[] jjtNodeName = {
    "parse",
    "Start",
    "and",
    "or",
    "function",
    "booleanSentence",
    "void",
    "sentence",
    "nestedSentence",
  };
}
/* JavaCC - OriginalChecksum=bf0e92abcd73ca4e549d74f7e4202e5f (do not edit this line) */
