/* Generated By:JJTree&JavaCC: Do not edit this line. FilterParserConstants.java */
package org.wonderdb.parser.jtree.filter;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSERT = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int DELETE = 7;
  /** RegularExpression Id. */
  int UPDATE = 8;
  /** RegularExpression Id. */
  int WHERE = 9;
  /** RegularExpression Id. */
  int CREATE = 10;
  /** RegularExpression Id. */
  int INDEX = 11;
  /** RegularExpression Id. */
  int UNIQUE = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int ON = 15;
  /** RegularExpression Id. */
  int TABLE = 16;
  /** RegularExpression Id. */
  int UNION = 17;
  /** RegularExpression Id. */
  int UNION_ALL = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int LPAREN = 20;
  /** RegularExpression Id. */
  int RPAREN = 21;
  /** RegularExpression Id. */
  int STRING = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"insert\"",
    "\"select\"",
    "\"delete\"",
    "\"update\"",
    "\"where\"",
    "\"create\"",
    "\"index\"",
    "\"unique\"",
    "\"and\"",
    "\"or\"",
    "\"on\"",
    "\"table\"",
    "\"union\"",
    "\"union all\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<STRING>",
  };

}
