/* Generated By:JavaCC: Do not edit this line. UQLParserTreeConstants.java Version 5.0 */
package org.wonderdb.parser.jtree.filter;

public interface UQLParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSTART = 1;
  public int JJTAND = 2;
  public int JJTSENTENCE = 3;
  public int JJTBOOLEANSENTENCE = 4;
  public int JJTGROPEDSENTENCE = 5;


  public String[] jjtNodeName = {
    "parse",
    "Start",
    "and",
    "sentence",
    "booleanSentence",
    "gropedSentence",
  };
}
/* JavaCC - OriginalChecksum=e7a5ea02486fce9cb92800ebec7804b2 (do not edit this line) */
