/* Generated By:JavaCC: Do not edit this line. UQLParserConstants.java */
package org.wonderdb.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSERT = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int DELETE = 7;
  /** RegularExpression Id. */
  int UPDATE = 8;
  /** RegularExpression Id. */
  int WHERE = 9;
  /** RegularExpression Id. */
  int SET = 10;
  /** RegularExpression Id. */
  int INTO = 11;
  /** RegularExpression Id. */
  int VALUES = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int FROM = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int LPAREN = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int EQUALS = 18;
  /** RegularExpression Id. */
  int NOTEQUAL = 19;
  /** RegularExpression Id. */
  int GT = 20;
  /** RegularExpression Id. */
  int LT = 21;
  /** RegularExpression Id. */
  int GE = 22;
  /** RegularExpression Id. */
  int LE = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int MUL = 27;
  /** RegularExpression Id. */
  int INT = 28;
  /** RegularExpression Id. */
  int LONG = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int FLOAT = 31;
  /** RegularExpression Id. */
  int STR = 32;
  /** RegularExpression Id. */
  int CREATE = 33;
  /** RegularExpression Id. */
  int INDEX = 34;
  /** RegularExpression Id. */
  int UNIQUE = 35;
  /** RegularExpression Id. */
  int ON = 36;
  /** RegularExpression Id. */
  int TABLE = 37;
  /** RegularExpression Id. */
  int SHOW = 38;
  /** RegularExpression Id. */
  int SCHEMA = 39;
  /** RegularExpression Id. */
  int Q = 40;
  /** RegularExpression Id. */
  int LIKE = 41;
  /** RegularExpression Id. */
  int STORAGE = 42;
  /** RegularExpression Id. */
  int IS_DEFAULT = 43;
  /** RegularExpression Id. */
  int YES = 44;
  /** RegularExpression Id. */
  int NO = 45;
  /** RegularExpression Id. */
  int ALTER = 46;
  /** RegularExpression Id. */
  int ADD = 47;
  /** RegularExpression Id. */
  int NULL = 48;
  /** RegularExpression Id. */
  int SHARD = 49;
  /** RegularExpression Id. */
  int REPLICASET = 50;
  /** RegularExpression Id. */
  int TO = 51;
  /** RegularExpression Id. */
  int IDX_COL_STRING = 52;
  /** RegularExpression Id. */
  int QUOTED_STRING = 53;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 54;
  /** RegularExpression Id. */
  int NUMBER = 55;
  /** RegularExpression Id. */
  int STRING = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"insert\"",
    "\"select\"",
    "\"delete\"",
    "\"update\"",
    "\"where\"",
    "\"set\"",
    "\"into\"",
    "\"values\"",
    "\"and\"",
    "\"from\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"int\"",
    "\"long\"",
    "\"double\"",
    "\"float\"",
    "\"string\"",
    "\"create\"",
    "\"index\"",
    "\"unique\"",
    "\"on\"",
    "\"table\"",
    "\"show\"",
    "\"schema\"",
    "\"?\"",
    "\"like\"",
    "\"storage\"",
    "\"is_default\"",
    "\"yes\"",
    "\"no\"",
    "\"alter\"",
    "\"add\"",
    "\"null\"",
    "\"shard\"",
    "\"replicaset\"",
    "\"to\"",
    "<IDX_COL_STRING>",
    "<QUOTED_STRING>",
    "<SINGLE_QUOTED_STRING>",
    "<NUMBER>",
    "<STRING>",
    "\"\\\"\"",
    "\".\"",
  };

}
